services:
  - type: web
    name: arkham-horror-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 wsgi:app
    envVars:
      - key: RENDER
        value: true
      - key: FLASK_ENV
        value: production
