services:
  - type: web
    name: arkham-horror-app
    env: python
    buildCommand: pip install -r requirements.txt
    # --- CAMBIO AQUÍ ---
    startCommand: gunicorn -k gevent -w 1 wsgi:app
    # ------------------
    envVars:
      - key: RENDER
        value: true
      - key: FLASK_ENV
        value: production
      # Asegúrate de tener la variable REDIS_URL aquí si no está inyectada por Render
      # - key: REDIS_URL
      #   value: <tu_redis_url_de_render>