services:
  - type: web
    name: arkham-horror-app
    env: python
    buildCommand: pip install -r requirements.txt
    # --- CAMBIO AQUÍ ---
    # Simplemente llama a gunicorn, leerá gunicorn.conf.py
    # y buscará 'app' en 'wsgi.py'
    startCommand: gunicorn wsgi:app
    # ------------------
    envVars:
      - key: RENDER
        value: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED # Buena práctica para logs en contenedores
        value: "1"
      - key: REDIS_URL
        value: redis://red-cvsqjii4d50c73d6eg60:6379 # Asegúrate que esté aquí